// This file is automatically generated by Firebase Studio.
'use server';

/**
 * @fileOverview A flow for generating automated security reports.
 *
 * - generateSecurityReport - A function that generates a security report based on provided events.
 * - SecurityReportInput - The input type for the generateSecurityReport function.
 * - SecurityReportOutput - The return type for the generateSecurityReport function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SecurityEventSchema = z.object({
  timestamp: z.string().describe('The timestamp of the security event.'),
  alertType: z.string().describe('The type of alert (e.g., suspicious movement, theft attempt, fire hazard, weapon detection).'),
  screenshotDataUri: z.string().describe(
    "A screenshot of the event, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
  ),
  details: z.string().describe('Detailed description of the event.'),
});

const SecurityReportInputSchema = z.object({
  date: z.string().describe('The date for which the security report is generated (YYYY-MM-DD).'),
  events: z.array(SecurityEventSchema).describe('An array of security events that occurred on the specified date.'),
});
export type SecurityReportInput = z.infer<typeof SecurityReportInputSchema>;

const SecurityReportOutputSchema = z.object({
  report: z.string().describe('A PDF report summarizing the security events.'),
});
export type SecurityReportOutput = z.infer<typeof SecurityReportOutputSchema>;

export async function generateSecurityReport(input: SecurityReportInput): Promise<SecurityReportOutput> {
  return generateSecurityReportFlow(input);
}

const generateReportPrompt = ai.definePrompt({
  name: 'generateReportPrompt',
  input: {schema: SecurityReportInputSchema},
  output: {schema: SecurityReportOutputSchema},
  prompt: `You are an AI that generates daily security reports.

  You will receive a list of security events that occurred on a specific date. Your task is to summarize these events and generate a comprehensive report in PDF format. The report should include the date, a summary of each event (including alert type, timestamp, and a brief AI-generated summary), and any relevant screenshots.

  Date: {{{date}}}
  Security Events:
  {{#each events}}
  - Timestamp: {{{timestamp}}}
    Alert Type: {{{alertType}}}
    Details: {{{details}}}
    Screenshot: {{media url=screenshotDataUri}}
  {{/each}}

  Please ensure that the generated report is well-formatted, easy to read, and provides a clear overview of the security situation for the given day.

  Include a title, date, and concise summary of each event including key details, timestamp and relevant screenshots. The entire output of this prompt MUST be the PDF data as a base64 encoded string.
`,
});

const generateSecurityReportFlow = ai.defineFlow(
  {
    name: 'generateSecurityReportFlow',
    inputSchema: SecurityReportInputSchema,
    outputSchema: SecurityReportOutputSchema,
  },
  async input => {
    const {output} = await generateReportPrompt(input);
    return output!;
  }
);
